# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Keep-It-Going' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keep-It-Going

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'

  target 'Keep-It-GoingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Keep-It-GoingUITests' do
    # Pods for testing
  end

end
